import type { NextPage } from "next";
import Head from "next/head";
import { Container } from "../../components/Container";
import { Main } from "../../components/Main";
import React from "react";
import { SolverTitle } from "../../components/solverComponents/solverTitle";

const SAT_Solver: NextPage = () => {
  return (
    <Container minHeight="100vh">
      <Head>
        <title>ProvideQ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* TODO: replace favicon */}
      </Head>
      <SolverTitle title="SAT Solver" text="For a given Boolean formula, this algorithm checks if there exists an interpretation that satisfies it." />
      <Main mb="20vh">

      </Main>
    </Container>
  );
};

export default SAT_Solver;
