import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { Container } from "../components/Container";
import { Hero } from "../components/Hero";
import { Main } from "../components/Main";
import { ProblemCard } from "../components/ProblemCard";
import { Text, Heading, Grid, GridItem } from "@chakra-ui/react";
import { ProblemChooser } from "../components/ProblemChooser";

const Home: NextPage = () => {
  return (
    <Container minHeight="100vh">
      <Head>
        <title>ProvideQ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* TODO: replace favicon */}
      </Head>

      <Hero title="ProvideQ" />
      <Main mb="20vh">
        <Text color="text" align="justify">
          Welcome to the ProvideQ frontend! Lorem ipsum dolor sit amet
          consectetur adipisicing elit. In, earum voluptas aspernatur itaque
          culpa modi a at explicabo assumenda praesentium quos quisquam expedita
          possimus unde sit iure illum architecto. Maiores voluptatum culpa odio
          quos exercitationem nemo laborum earum dolores expedita inventore odit
          delectus vel autem ipsa quam tenetur ab, illo enim reiciendis debitis
          quasi minima. Voluptatum fugit consequatur aspernatur neque. Id
          ducimus debitis animi veritatis, alias deleniti voluptates repudiandae
          officia aliquam qui accusantium. Ullam a, animi quos excepturi nemo
          iste, expedita placeat qui ipsam error nostrum dolores tempore eaque
          nobis ipsa consequuntur tenetur, cupiditate repellendus illum hic!
          Debitis, repellat totam.
        </Text>

        <Heading as="h2" size="xl" pt="10">
          Solve a problem
        </Heading>

        <ProblemChooser />
      </Main>
    </Container>
  );
};

export default Home;
