import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { Container } from "../components/Container";
import { ProblemInputButtonPanel } from "../components/ProblemInputButtonPanel";
import { ProblemSolverTitle } from "../components/ProblemSolverTitle";
import { Main } from "../components/Main";
import { GoButton } from "../components/GoButton";
import { Text, Textarea, Divider} from "@chakra-ui/react";
import { ProblemTextArea } from "../components/ProblemTextArea";
import React from "react";

const SAT_Solver: NextPage = () => {
  let problemTextAreaRef: React.MutableRefObject<ProblemTextArea | null> = React.createRef();
  return (
    <Container minHeight="100vh">
      <Head>
        <title>ProvideQ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* TODO: replace favicon */}
      </Head>
      <ProblemSolverTitle title="SAT Solver" text="For a given Boolean formula, this algorithm checks if there exists an interpretation that satisfies it." />
      <Main mb="20vh">
        <ProblemTextArea ref={problemTextAreaRef}/>
        <ProblemInputButtonPanel helpBody={
          <Text>there is no help where you are going</Text>  
        } problemText={() => problemTextAreaRef.current?.state.problemString}/>
        <Divider />
        <GoButton />
      </Main>
    </Container>
  );
};

export default SAT_Solver;
