import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { Container } from "../components/Container";
import { ProblemInputButtonPanel } from "../components/ProblemInputButtonPanel";
import { ProblemSolverTitle } from "../components/ProblemSolverTitle";
import { Main } from "../components/Main";
import { GoButton } from "../components/GoButton";
import { Text, Textarea, Divider} from "@chakra-ui/react";

const SAT_Solver: NextPage = () => {
  return (
    <Container minHeight="100vh">
      <Head>
        <title>ProvideQ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* TODO: replace favicon */}
      </Head>
      <ProblemSolverTitle title="SAT Solver" text="For a given Boolean formula, this algorithm checks if there exists an interpretation that satisfies it." />
      <Main mb="20vh">
        <Textarea placeholder="(p∨u∨t)∧(y∨o∨u∨¬r)∧(p∨r∨¬o∨b∨l∨e∨¬m)∧(h∨¬e∨r∨e)"></Textarea>
        <ProblemInputButtonPanel helpBody={
          <Text>there is no help where you are going</Text>
        }/>
        <Divider />
        <GoButton />
      </Main>
    </Container>
  );
};

export default SAT_Solver;
