import { Divider, Textarea } from "@chakra-ui/react";
import Head from "next/head";
import { ReactElement, useState } from "react";
import { Container } from "../Container";
import { EditorControls } from "./EditorControls";

export interface TextInputMaskProperties {
  textPlaceholder: string;
  text: string;
  onTextChanged: (value: string) => void;
  body?: ReactElement;
}

export const TextInputMask = (props: TextInputMaskProperties) => {
  const [errorString, setErrorString] = useState("");

  function onTextChanged(text: string): void {
    try {
      props.onTextChanged(text);

      setErrorString("");
    } catch (e: any) {
      setErrorString(e.message);
    }
  }

  return (
    <Container gap="1rem">
      <Head>
        <title>ProvideQ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* TODO: replace favicon */}
      </Head>

      <EditorControls
        errorText={errorString}
        idleText={props.textPlaceholder + " 👇"}
        onUpload={onTextChanged}
        editorContent={props.text}
      />
      <Textarea
        placeholder={props.textPlaceholder}
        value={props.text}
        minHeight="10rem"
        isInvalid={errorString != ""}
        onChange={(x) => onTextChanged(x.target.value)}
      />

      <Divider />

      {props.body}
    </Container>
  );
};
