import { Divider, Text, Textarea } from "@chakra-ui/react";
import Head from "next/head";
import React, { ReactElement, useState } from "react";
import { Container } from "../Container";
import { Main } from "../Main";
import { InputButtonPanel } from "./buttons/InputButtonPanel";
import { Help } from "./SAT/Help";
import { SolverTitle } from "./SolverTitle";

export interface TextInputMaskProperties {
    title: string;
    description: string;
    textPlaceholder: string;
    onTextChanged: (text: string) => void;
    body?: ReactElement;
}

export const TextInputMask = (props: TextInputMaskProperties) => {
    const [text, setText] = useState<string>("");
    const [errorString, setErrorString] = useState("");

    function onTextChanged(text: string): void {
        try {
            setText(text);
            props.onTextChanged(text);

            setErrorString('');
        } catch (e: any) {
            setErrorString(e.message);
        }
    }

    return (
        <Container minHeight="100vh">
            <Head>
                <title>ProvideQ</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
                {/* TODO: replace favicon */}
            </Head>
            <SolverTitle title={props.title}
                         text={props.description}/>
            <Main mb="20vh">

                <Textarea placeholder={props.textPlaceholder}
                          value={text}
                          minHeight="10rem"
                          isInvalid={errorString != ""}
                          onChange={x => onTextChanged(x.target.value)}/>

                <Text backgroundColor="tomato">{errorString}</Text>

                <InputButtonPanel
                    helpBody={<Help/>}
                    problemString={text}
                    setProblemString={x => onTextChanged(x as string)}
                    uploadString={str => str}
                    downloadString={str => str}/>

                <Divider/>

                {props.body}
            </Main>
        </Container>
    );
};