import Head from "next/head";
import React from "react";
import type { NextPage } from "next";
import { Container } from "../../components/Container";
import { Main } from "../../components/Main";
import { SolverTitle } from "../../components/solvers/SolverTitle";
import { TextArea } from "../../components/solvers/SAT/TextArea";
import { Help } from "../../components/solvers/SAT/Help";
import { InputButtonPanel } from "../../components/solvers/buttons/InputButtonPanel";
import { ProgressHandler } from "../../components/solvers/ProgressHandler";
import { Divider } from "@chakra-ui/react";

const SAT: NextPage = () => {
  let TextAreaRef: React.MutableRefObject<TextArea | null> = React.createRef();
  return (
    <Container minHeight="100vh">
      <Head>
        <title>ProvideQ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* TODO: replace favicon */}
      </Head>
      <SolverTitle title="SAT Solver" text="For a given Boolean formula, this algorithm checks if there exists an interpretation that satisfies it." />
      <Main mb="20vh">
      <TextArea ref={TextAreaRef} />
      <InputButtonPanel 
        helpBody={<Help/>}
        problemText={() => TextAreaRef.current?.state.problemString}
        setProblemText={((code: string) => TextAreaRef.current?.setProblemString(code))}
        />
      <Divider />
      <ProgressHandler />
      </Main>
    </Container>
  );
};

export default SAT;
